name: Create Release

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Bump version and push tag
        id: tag_version
        uses: miguelfito/github-bump-and-tag-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_sha: ${{ GITHUB.SHA }}
          tag_prefix: ""

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: ${{ steps.tag_version.outputs.new_tag }}
          body: |
            Update from ${{ steps.tag_version.outputs.previous_tag }} to ${{ steps.tag_version.outputs.new_tag }}
            Changelog: ${{ steps.tag_version.outputs.changelog }}